[package]
name = "sfc-fix"
version = "0.1.0"
edition = "2021"

[dependencies]
winreg = "0.10.1"
rfd = "0.7.0"

[dependencies.regex]
version = "1.5.4"
default-features = false
features = ["std"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = 0